language: ruby
rvm:
  - 2.4.0
# 设置只监听哪个分支
branches:
  only:
    - source
# 缓存，可以节省集成的时间
cache:
  apt: true
  gem: true
  directories:
    - node_modules
# tarvis生命周期执行顺序详见官网文档
before_install:
  - git config --global user.name "mapoio"
  - git config --global user.email "one@mapo.io"
  - export TZ='Asia/Shanghai'
  - chmod +x _travis.sh
install:
  - gem install jekyll
  - gem install jekyll-paginate
  - gem install jekyll-sitemap
script:
  - jekyll build
after_success:
  - ./_travis.sh

env:
 global:
   - GH_USER_NAME: mapoio
   - GH_REF: github.com/mapoio/mapoio.github.io.git
   - GITEE_USER_NAME: amazed
   - GITEE_REF: gitee.com/amazed/amazed.git
   - CODING_USER_NAME: sport
   - CODING_REF: git.coding.net/sport/sport.git