# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 麻婆酱
subtitle: '前沿观察'
description: '种一棵树的最好时间是十年前，其次是现在'
keywords: Frontend, Web Develop, Node.js, TypeScript, JavaScript
author: Mapo
language: zh-CN
timezone: ''
bio: 种一棵树的最好时间是十年前，其次是现在

favicon: images/favicon.png
blog_logo: images/favicon.png
header_image: images/background.jpg

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://mapo.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-casper

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ''

footer:
  RSS: /atom.xml

feed:
    limit: 20
    order_by: 'date'
    tag_dir: 'tag'
    category_dir: 'category'
    rss:
        enable: true
        template: 'themes/hexo-theme-casper/layout/_alternate/rss.ejs'
        output: 'rss.xml'
    atom:
        enable: true
        template: 'themes/hexo-theme-casper/layout/_alternate/atom.ejs'
        output: 'atom.xml'
    jsonFeed:
        enable: true
        template: 'themes/hexo-theme-casper/layout/_alternate/json.ejs'
        output: 'feed.json'

math:
  engine: 'mathjax'
  mathjax: 
    src: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  per_page: false

flowchart:
  raphael:   https://cdn.jsdelivr.net/npm/raphael@2.3.0/raphael.min.js
  flowchart: https://cdn.jsdelivr.net/gh/adrai/flowchart.js@1.13.0/release/flowchart.min.js
  options: # options used for `drawSVG`

mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: true  # default true
  url: https://cdn.jsdelivr.net/npm/mermaid@8.5.1/dist/mermaid.min.js
  options:  # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
    theme: default

cdn:
  enable: true
  url: 'https://cdn.jsdelivr.net/mapoio/mapoio.github.io'
