name: Deploy Hexo
on:
  push:
    branches:
      - source
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
      run: |
        npm list -g --depth 0
        npm -g i yarn
        yarn
        yarn build

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      env:
        # ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        branch: master
        folder: public